// Written by Paul Clevett
// (C)Copyright Wolf Software Systems Ltd
// https://wolf.uk.com

//! WolfStack Pools — provision a federated tenant cluster of N VMs
//! from a single SP-side action.
//!
//! A "pool" represents an order: "give customer X a 3-VM WolfStack
//! cluster on backend Y". The driver fans out N VM creates with
//! cloud-init payloads that:
//!
//!   1. Pre-write the shared cluster_secret + per-VM join-token
//!      under /etc/wolfstack/ BEFORE setup.sh runs (setup.sh:260
//!      preserves existing config on re-runs, so this works).
//!   2. On the leader VM only, pre-write the federation token to
//!      /etc/wolfstack/federation_tokens.json so the SP can poll
//!      /api/federation/status as soon as the daemon is up.
//!   3. Run setup.sh → daemon up.
//!   4. On the leader, POST `/api/tenants/self-register` back to
//!      the SP with the bootstrap_token; SP validates against the
//!      pending pool and registers the tenant.
//!   5. On followers, POST `/api/cluster/bootstrap-add` to the
//!      leader with X-WolfStack-Secret = pool_secret + own
//!      join-token; leader joins them into its cluster.
//!
//! The bootstrap_token, pool_secret, federation_token, and
//! per-VM join_tokens are all generated by the SP and embedded in
//! cloud-init. The SP sees the full state machine — provisioning
//! → leader_up → followers_joining → live — through XO inventory
//! polling and the self-register callback.
//!
//! Driver layer:
//!
//!   * `Backend::Xo`     — `xo_driver` (this module): wraps existing
//!     `xo::XoClient::create_vm` with cloud-init.
//!   * `Backend::Proxmox`/`Backend::Native` — trait stubs for now;
//!     they return a clear `not_yet_implemented` error to the API.
//!     The user agreed to phased delivery (XO first, Proxmox next
//!     session, native after) so these are explicit not-yet, not
//!     half-implementations.

use serde::{Deserialize, Serialize};
use std::sync::Mutex;

pub mod cloud_init;
pub mod native_driver;
pub mod orchestrator;
pub mod proxmox_driver;
pub mod xo_driver;

// ─── Types ────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Backend {
    Xo,
    Proxmox,
    Native,
}

impl Backend {
    pub fn as_str(&self) -> &'static str {
        match self { Backend::Xo => "xo", Backend::Proxmox => "proxmox", Backend::Native => "native" }
    }
}

/// What the operator submits when creating a pool. Backend-agnostic
/// — driver-specific binding (e.g. which XO instance, which template
/// uuid) lives in `backend_ref`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PoolSpec {
    pub backend: Backend,

    /// Display name of the customer / cluster.
    pub tenant_name: String,

    /// Backend-specific reference. For XO this is the registered
    /// XO instance id (`/api/xo/pools` row id); the driver looks
    /// up the connection from there.
    pub backend_ref: String,

    /// Backend-specific template / image identifier. For XO this
    /// is the template UUID returned by `/api/xo/pools/{id}/templates`.
    pub template: String,

    /// Number of VMs in the pool. Must be >= 1. v1: 1..=10.
    pub vm_count: u32,

    /// Per-VM resources.
    pub vcpu: u32,
    pub memory_mb: u32,
    /// Disk GB — drivers honour this if the backend supports
    /// resize-on-clone (XO does via memoryMax/cpus, not disk yet).
    /// Recorded for future use; XO v1 ignores it (template default).
    #[serde(default)]
    pub disk_gb: u32,

    /// Optional override for the public URL the leader VM uses to
    /// reach the SP. Empty → derived from the SP's primary IP.
    /// This is the URL the leader cloud-init will POST to for
    /// /api/tenants/self-register, AND the URL the leader will
    /// use to fetch setup.sh from the SP install proxy.
    #[serde(default)]
    pub sp_url: String,

    /// Hostname prefix for the VMs. Defaults to the tenant name
    /// (sanitised). Each VM ends up named `{prefix}-1`, `{prefix}-2`, ...
    #[serde(default)]
    pub hostname_prefix: String,
}

/// What the SP needs to remember about a pool to drive its lifecycle.
/// Persisted to /etc/wolfstack/pools.json.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Pool {
    pub id: String,
    pub spec: PoolSpec,
    /// `creating` → `provisioning` → `leader_up` → `live` → `failed`/`destroyed`.
    pub status: String,

    /// Empty until the leader self-registers. `https://...:8553`.
    #[serde(default)]
    pub leader_url: String,

    /// Tenant id this pool federated as (foreign key into tenants.json).
    /// Empty until self-register completes.
    #[serde(default)]
    pub tenant_id: String,

    /// Backend VM handles (uuid + assigned hostname). Index 0 is
    /// always the leader.
    #[serde(default)]
    pub vms: Vec<VmHandle>,

    /// Bootstrap token — single-use, validates the leader's
    /// /api/tenants/self-register callback. Stored XOR-obfuscated.
    pub bootstrap_token_enc: String,
    /// One-time use — set to true once self-register has consumed it.
    #[serde(default)]
    pub bootstrap_consumed: bool,

    /// Shared cluster secret across the pool's VMs. Stored
    /// XOR-obfuscated. Used as X-WolfStack-Secret for inter-node
    /// auth + the new /api/cluster/bootstrap-add endpoint.
    pub pool_secret_enc: String,

    /// Federation token planted on the leader at first boot.
    /// Stored XOR-obfuscated; pushed back into tenants.json so the
    /// SP can poll federation status without prompting the user.
    pub federation_token_enc: String,

    /// RFC3339 timestamps so the orchestrator can time-out stuck
    /// pools (default 30 min from `created_at` to leader_up).
    pub created_at: String,
    #[serde(default)]
    pub leader_up_at: String,
    #[serde(default)]
    pub live_at: String,

    /// Last error surfaced from a driver / orchestrator step. Empty
    /// when healthy. Visible in the UI tile so the operator can see
    /// what failed without digging into the daemon log.
    #[serde(default)]
    pub last_error: String,
}

/// Per-VM handle returned by the driver. Used by the orchestrator
/// to poll IPs from the backend and (for destroy) clean up.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmHandle {
    /// Backend-native id (XO uuid, PVE vmid, libvirt domain name).
    pub backend_id: String,
    pub hostname: String,
    /// Per-VM unique join-token (planted in /etc/wolfstack/join-token).
    /// Used by /api/cluster/bootstrap-add when this VM joins the
    /// leader. Stored XOR-obfuscated.
    pub join_token_enc: String,
    /// Leader is index 0 in `Pool::vms` AND has `is_leader=true`
    /// here for clarity (defence in depth — orchestrator code asserts
    /// they agree).
    pub is_leader: bool,
    /// IPv4 address — empty until the orchestrator observes the VM
    /// has come up. Used to drive the join calls.
    #[serde(default)]
    pub ipv4: String,
    /// Has this follower been added to the leader's cluster yet?
    /// Always false for the leader (it doesn't join itself).
    /// Set true once /api/cluster/bootstrap-add returns success.
    #[serde(default)]
    pub joined: bool,
}

// ─── Driver dispatch ──────────────────────────────────────────────
//
// Closed enum of backends — no dyn trait, no async-trait dep.
// Each driver module exposes plain async functions; the dispatch
// helpers below match on the backend and call into the right one.
// Backends not yet implemented return `not_yet_implemented` errors
// — explicit, surfaced to the UI. This is NOT a half-implementation
// (cf. global rule); the user agreed to phased delivery (XO first,
// Proxmox + native in following sessions).

/// Provision N VMs per the spec. Index 0 = leader.
pub async fn driver_provision(
    backend: Backend,
    spec: &PoolSpec,
    bootstrap: &BootstrapMaterial,
) -> Result<Vec<VmHandle>, String> {
    match backend {
        Backend::Xo => xo_driver::provision(spec, bootstrap).await,
        Backend::Proxmox => proxmox_driver::provision(spec, bootstrap).await,
        Backend::Native => native_driver::provision(spec, bootstrap).await,
    }
}

pub async fn driver_destroy(pool: &Pool) -> Result<(), String> {
    match pool.spec.backend {
        Backend::Xo => xo_driver::destroy(&pool.vms).await,
        Backend::Proxmox => proxmox_driver::destroy(&pool.vms).await,
        Backend::Native => native_driver::destroy(pool).await,
    }
}

pub async fn driver_observe_ips(
    backend: Backend,
    vms: &[VmHandle],
) -> Result<Vec<Option<String>>, String> {
    match backend {
        Backend::Xo => xo_driver::observe_ips(vms).await,
        Backend::Proxmox => proxmox_driver::observe_ips(vms).await,
        Backend::Native => native_driver::observe_ips(vms).await,
    }
}

/// Pre-generated bootstrap secrets the driver embeds in cloud-init.
/// Generated by `Pool::new` so each driver gets the same material.
pub struct BootstrapMaterial {
    pub bootstrap_token: String,
    pub pool_secret: String,
    pub federation_token: String,
    /// Per-VM join tokens — length = vm_count. Index 0 = leader.
    pub join_tokens: Vec<String>,
    /// SP URL the leader cloud-init posts back to.
    pub sp_url: String,
}

// ─── Bootstrap material generation ────────────────────────────────

fn random_token(len: usize) -> String {
    use rand::RngCore;
    let alphabet = b"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    let mut bytes = vec![0u8; len];
    rand::rngs::OsRng.fill_bytes(&mut bytes);
    bytes.iter()
        .map(|b| alphabet[(*b as usize) % alphabet.len()] as char)
        .collect()
}

impl BootstrapMaterial {
    pub fn generate(vm_count: u32, sp_url: &str) -> Self {
        Self {
            bootstrap_token: random_token(48),
            pool_secret: random_token(48),
            federation_token: random_token(48),
            join_tokens: (0..vm_count).map(|_| random_token(48)).collect(),
            sp_url: sp_url.trim_end_matches('/').to_string(),
        }
    }
}

// ─── Persistence ──────────────────────────────────────────────────

const POOLS_FILE: &str = "/etc/wolfstack/pools.json";

#[derive(Default)]
pub struct PoolStore {
    pools: Vec<Pool>,
}

static POOL_STORE_LOCK: Mutex<()> = Mutex::new(());

impl PoolStore {
    pub fn load() -> Self {
        let pools = match std::fs::read_to_string(POOLS_FILE) {
            Ok(s) => serde_json::from_str(&s).unwrap_or_default(),
            Err(_) => Vec::new(),
        };
        Self { pools }
    }

    fn save_locked(pools: &[Pool]) -> Result<(), String> {
        let s = serde_json::to_string_pretty(pools).map_err(|e| format!("serialize: {}", e))?;
        let _ = std::fs::create_dir_all("/etc/wolfstack");
        let tmp = format!("{}.tmp", POOLS_FILE);
        std::fs::write(&tmp, &s).map_err(|e| format!("write: {}", e))?;
        std::fs::rename(&tmp, POOLS_FILE).map_err(|e| format!("rename: {}", e))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            // pools.json holds bootstrap tokens, federation tokens,
            // and the shared cluster secret — all obfuscated, but
            // still keep the file 0600. /etc/wolfstack/ is 0700 from
            // setup.sh; this is defence in depth.
            let _ = std::fs::set_permissions(POOLS_FILE,
                std::fs::Permissions::from_mode(0o600));
        }
        Ok(())
    }

    pub fn list(&self) -> Vec<Pool> { self.pools.clone() }

    pub fn get(&self, id: &str) -> Option<Pool> {
        self.pools.iter().find(|p| p.id == id).cloned()
    }

    /// Atomically (under POOL_STORE_LOCK + fresh disk re-read) find
    /// the pool whose `bootstrap_token` matches, mark it consumed,
    /// and persist.
    ///
    /// * `Ok(Some(pool))` — consumed; pool returned with
    ///   `bootstrap_consumed=true` so the caller can fill in
    ///   tenant_id / leader_url / status in the same `update` call.
    /// * `Ok(None)` — no pending pool with that token (already
    ///   consumed, or never existed). Surface as 401 to the caller.
    /// * `Err(e)` — disk write failed. Surface as 500 so the leader
    ///   retries; never silently treat this as "not found", because
    ///   that would re-open the single-use window on retry.
    ///
    /// Race-safe: two concurrent self-register POSTs with the same
    /// bootstrap_token can't both succeed — the second sees
    /// `bootstrap_consumed=true` after the first's persisted update.
    pub fn consume_bootstrap_atomic(token: &str) -> Result<Option<Pool>, String> {
        let _g = POOL_STORE_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let mut current: Vec<Pool> = match std::fs::read_to_string(POOLS_FILE) {
            Ok(s) => serde_json::from_str(&s).unwrap_or_default(),
            Err(_) => Vec::new(),
        };
        let idx = match current.iter().position(|p| {
            !p.bootstrap_consumed
                && crate::xo::deobfuscate_token(&p.bootstrap_token_enc) == token
        }) {
            Some(i) => i,
            None => return Ok(None),
        };
        current[idx].bootstrap_consumed = true;
        Self::save_locked(&current)?;
        Ok(Some(current[idx].clone()))
    }

    pub fn add(&mut self, pool: Pool) -> Result<(), String> {
        let _g = POOL_STORE_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        // Reload under lock to absorb any concurrent writes.
        let mut current: Vec<Pool> = match std::fs::read_to_string(POOLS_FILE) {
            Ok(s) => serde_json::from_str(&s).unwrap_or_default(),
            Err(_) => Vec::new(),
        };
        if current.iter().any(|p| p.id == pool.id) {
            return Err(format!("pool {} already exists", pool.id));
        }
        current.push(pool);
        Self::save_locked(&current)?;
        self.pools = current;
        Ok(())
    }

    /// Persist a mutation done on a clone of a pool. Looks up by id,
    /// replaces, saves.
    pub fn update(&mut self, pool: Pool) -> Result<(), String> {
        let _g = POOL_STORE_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let mut current: Vec<Pool> = match std::fs::read_to_string(POOLS_FILE) {
            Ok(s) => serde_json::from_str(&s).unwrap_or_default(),
            Err(_) => Vec::new(),
        };
        let idx = current.iter().position(|p| p.id == pool.id)
            .ok_or_else(|| format!("pool {} not found", pool.id))?;
        current[idx] = pool;
        Self::save_locked(&current)?;
        self.pools = current;
        Ok(())
    }

    pub fn remove(&mut self, id: &str) -> Result<(), String> {
        let _g = POOL_STORE_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let mut current: Vec<Pool> = match std::fs::read_to_string(POOLS_FILE) {
            Ok(s) => serde_json::from_str(&s).unwrap_or_default(),
            Err(_) => Vec::new(),
        };
        let before = current.len();
        current.retain(|p| p.id != id);
        if current.len() == before {
            return Err(format!("pool {} not found", id));
        }
        Self::save_locked(&current)?;
        self.pools = current;
        Ok(())
    }
}

// ─── Shared helpers ───────────────────────────────────────────────

/// Sanitise a hostname prefix to RFC 1123 (alphanumeric + hyphen).
/// Capped at 58 chars so each driver can append `-N` for the
/// per-VM index. Used by all three drivers (XO / Proxmox / native).
pub fn safe_hostname_prefix(s: &str) -> String {
    let cleaned: String = s.chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-')
        .take(58)
        .collect();
    if cleaned.is_empty() { "wolfstack".into() } else { cleaned }
}

// ─── New-pool helper ──────────────────────────────────────────────

/// Build the Pool record + bootstrap material for a fresh order.
/// The caller hands the driver the BootstrapMaterial so cloud-init
/// can embed the secrets, then persists the resulting `Pool` (with
/// the obfuscated copies) via `PoolStore::add`.
pub fn new_pool(spec: PoolSpec) -> (Pool, BootstrapMaterial) {
    let id = uuid::Uuid::new_v4().to_string();
    let sp_url = spec.sp_url.clone();
    let mat = BootstrapMaterial::generate(spec.vm_count, &sp_url);

    let pool = Pool {
        id,
        bootstrap_token_enc: crate::xo::obfuscate_token(&mat.bootstrap_token),
        pool_secret_enc: crate::xo::obfuscate_token(&mat.pool_secret),
        federation_token_enc: crate::xo::obfuscate_token(&mat.federation_token),
        bootstrap_consumed: false,
        spec,
        status: "creating".into(),
        leader_url: String::new(),
        tenant_id: String::new(),
        vms: Vec::new(),
        created_at: chrono::Utc::now().to_rfc3339(),
        leader_up_at: String::new(),
        live_at: String::new(),
        last_error: String::new(),
    };
    (pool, mat)
}

