// Written by Paul Clevett
// (C)Copyright Wolf Software Systems Ltd
// https://wolf.uk.com

//! Incremental VM replication using QEMU persistent dirty bitmaps.
//!
//! A VM disk cannot be replicated the way a container rootfs is. It is
//! one enormous file, so file-level change detection degenerates to
//! "send the whole disk", and reading a running guest's qcow2 at file
//! level yields a torn image — `vms::manager` already refuses to clone a
//! running VM for precisely that reason.
//!
//! QEMU solves this in the block layer. A *dirty bitmap* attached to the
//! disk records which clusters the guest has written since the bitmap was
//! last cleared; `blockdev-backup` with `sync: "bitmap"` then copies only
//! those clusters into a target image. Made `persistent`, the bitmap is
//! stored inside the qcow2 and survives a VM restart, so replication does
//! not restart from a full copy every time the guest reboots.
//!
//! The round is:
//!
//! 1. `block-dirty-bitmap-add` once, persistent, when HA is enabled.
//! 2. Create an empty qcow2 of the same virtual size as the delta target.
//! 3. `blockdev-add` that file as a node, `blockdev-backup` the dirty
//!    clusters into it, wait for the job, `blockdev-del` the node.
//! 4. Ship the delta to the replica.
//! 5. Replica: `qemu-img rebase -u` to point the delta at its own copy,
//!    then `qemu-img commit` to write the clusters down into it.
//!
//! **Every QMP field below is taken from QEMU's own QAPI schema**, pinned
//! at v9.1.0 — `qapi/block-core.json` and `qapi/job.json`. Command names,
//! enum spellings and optionality are cited inline at each call rather
//! than recalled, because a wrong enum spelling here fails at runtime on
//! a user's machine, not at compile time on ours.
//!
//! ## The durability rule
//!
//! `bitmap-mode: "on-success"` clears the copied bits when the backup job
//! succeeds. That happens BEFORE the delta reaches the replica, so if the
//! transfer then fails those clusters are no longer in any future delta
//! and the replica would silently diverge — the worst possible failure for
//! an HA system, because it looks healthy.
//!
//! The delta file is therefore the unit of durability: it stays on disk
//! until a replica confirms it applied, and while one is pending we do
//! NOT take a new backup — the pending delta is retried first, preserving
//! strict ordering. If a pending delta is lost, the subject is marked as
//! needing a full resync rather than quietly continuing.

use serde::{Deserialize, Serialize};
use std::process::Command;

/// Bitmap name attached to a VM's disk. One per subject, not per replica:
/// a delta is identical for every replica, so it is taken once and shipped
/// to each, with per-replica state tracking who has applied it.
///
/// Must be under 1024 bytes (`BlockDirtyBitmapAdd.name`, block-core.json).
pub fn bitmap_name(vm: &str) -> String {
    format!("wolfha-{}", vm)
}

/// A delta awaiting confirmation from at least one replica.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingDelta {
    /// Staged delta qcow2 on the primary.
    pub path: String,
    /// When it was taken (unix seconds).
    pub taken_at: u64,
    /// Node ids that have confirmed applying it.
    #[serde(default)]
    pub applied_by: Vec<String>,
}

/// One QMP call against a VM's monitor.
fn qmp(vm: &str, command: &str, args: Option<serde_json::Value>) -> Result<serde_json::Value, String> {
    crate::vms::manager::qmp_command(vm, command, args)
}

/// Resolve the QEMU block node that backs `disk_path` for this VM.
///
/// `blockdev-backup.device` takes "the device name or node-name of a root
/// node" (block-core.json), and WolfStack starts VMs without naming their
/// nodes, so the name is autogenerated and must be looked up at runtime
/// rather than assumed.
///
/// `query-block` returns `[BlockInfo]`; each entry carries `device` and an
/// `inserted` `BlockDeviceInfo` whose `file` is the backing filename. We
/// match on the filename so the right disk is found even on a VM with
/// several drives.
pub fn resolve_disk_node(vm: &str, disk_path: &str) -> Result<String, String> {
    let blocks = qmp(vm, "query-block", None)?;
    let arr = blocks.as_array().ok_or("query-block did not return a list")?;

    // Collect (match-strength, node-reference) for every inserted medium.
    // Strength 0 = exact string, 1 = same resolved path, 2 = same file name.
    // Strongest wins, and a file-name match is only trusted when it is
    // UNIQUE: a VM with two disks of the same name in different directories
    // must not have the bitmap attached to whichever came first.
    let mut candidates: Vec<(u8, String)> = Vec::new();
    for b in arr {
        let Some(inserted) = b.get("inserted") else { continue }; // empty tray
        let file = inserted.get("file").and_then(|f| f.as_str()).unwrap_or("");
        let Some(strength) = match_strength(file, disk_path) else { continue };
        // Prefer the node-name. QEMU auto-generates one (`#block134`) when
        // the drive was not declared with an explicit node-name, and it
        // accepts that form as a reference — verified against a live QEMU,
        // as was the `device` id form, so either works.
        let reference = inserted
            .get("node-name")
            .and_then(|n| n.as_str())
            .filter(|n| !n.is_empty())
            .or_else(|| b.get("device").and_then(|d| d.as_str()).filter(|d| !d.is_empty()));
        if let Some(r) = reference {
            candidates.push((strength, r.to_string()));
        }
    }

    for strength in 0u8..=2 {
        let at: Vec<&(u8, String)> = candidates.iter().filter(|(s, _)| *s == strength).collect();
        match at.len() {
            0 => continue,
            1 => return Ok(at[0].1.clone()),
            n if strength == 2 => {
                return Err(format!(
                    "{} disks on VM '{}' share the file name of {} — cannot tell which to \
                     replicate. Give the VM's disks distinct file names.",
                    n, vm, disk_path
                ));
            }
            // Two disks reporting the identical path is QEMU serving the
            // same image twice; either reference is the same disk.
            _ => return Ok(at[0].1.clone()),
        }
    }

    Err(format!(
        "no QEMU block node is serving {} on VM '{}' — the disk path in the VM \
         config must match what QEMU actually opened",
        disk_path, vm
    ))
}

/// Do QEMU's reported filename and our configured path name the same disk?
///
/// `query-block` reports the filename **as QEMU was given it on the command
/// line**, which is not necessarily the string we hold. Against a live QEMU
/// launched with a relative path it reported `qmptest.qcow2` while our
/// configured path was absolute, and an exact comparison found nothing —
/// so VM replication would have failed to locate its own disk.
///
/// Compared in widening steps, returning how strongly they match:
/// `0` identical strings, `1` same resolved path (collapsing symlinks and
/// `..`), `2` same file name, `None` for no match. The caller only trusts a
/// file-name match when it is unambiguous.
fn match_strength(reported: &str, configured: &str) -> Option<u8> {
    if reported.is_empty() {
        return None;
    }
    if reported == configured {
        return Some(0);
    }
    let canon = |p: &str| std::fs::canonicalize(p).ok();
    if let (Some(a), Some(b)) = (canon(reported), canon(configured))
        && a == b
    {
        return Some(1);
    }
    let name = |p: &str| {
        std::path::Path::new(p)
            .file_name()
            .map(|n| n.to_string_lossy().to_string())
    };
    match (name(reported), name(configured)) {
        (Some(a), Some(b)) if a == b => Some(2),
        _ => None,
    }
}

/// Convenience wrapper used by the tests and by `bitmap_state`.
fn same_disk(reported: &str, configured: &str) -> bool {
    match_strength(reported, configured).is_some()
}

/// State of our bitmap on a node, as reported by `query-block`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BitmapState {
    /// Not present — needs creating, and the replica needs a full seed.
    Missing,
    /// Present and recording writes.
    Recording,
    /// Present but not recording. A bitmap that stops recording is not
    /// tracking guest writes, so any delta built from it is incomplete.
    NotRecording,
    /// Persistent bitmap that was stored improperly (QEMU killed rather
    /// than shut down). `BlockDirtyInfo.inconsistent` — "This bitmap
    /// cannot be used. To remove it, use block-dirty-bitmap-remove."
    Inconsistent,
}

/// Inspect our bitmap on the VM's disk node.
pub fn bitmap_state(vm: &str, disk_path: &str) -> Result<BitmapState, String> {
    let want = bitmap_name(vm);
    let blocks = qmp(vm, "query-block", None)?;
    let arr = blocks.as_array().ok_or("query-block did not return a list")?;
    for b in arr {
        let Some(inserted) = b.get("inserted") else { continue };
        // Same path-form tolerance as `resolve_disk_node`: QEMU reports the
        // filename as it was launched with, which is not necessarily the
        // string we hold. An exact comparison here would report the bitmap
        // missing on a VM that has one, and the caller would then demand a
        // full re-seed on every round.
        if !same_disk(
            inserted.get("file").and_then(|f| f.as_str()).unwrap_or(""),
            disk_path,
        ) {
            continue;
        }
        // BlockDeviceInfo.dirty-bitmaps: ['BlockDirtyInfo'] (optional).
        let bitmaps = inserted.get("dirty-bitmaps").and_then(|d| d.as_array());
        let Some(bitmaps) = bitmaps else { return Ok(BitmapState::Missing) };
        for bm in bitmaps {
            if bm.get("name").and_then(|n| n.as_str()) != Some(want.as_str()) {
                continue;
            }
            // `inconsistent` is optional and implies persistent; check it
            // first because such a bitmap must be removed, not used.
            if bm.get("inconsistent").and_then(|v| v.as_bool()).unwrap_or(false) {
                return Ok(BitmapState::Inconsistent);
            }
            return Ok(if bm.get("recording").and_then(|v| v.as_bool()).unwrap_or(false) {
                BitmapState::Recording
            } else {
                BitmapState::NotRecording
            });
        }
        return Ok(BitmapState::Missing);
    }
    Err(format!("disk {} not found on VM '{}'", disk_path, vm))
}

/// Create the persistent bitmap. Called once when HA is enabled for a VM,
/// and again after a full seed.
///
/// `persistent: true` stores the bitmap in the qcow2 so a guest reboot
/// does not force a full recopy. block-core.json is explicit that "For now
/// only Qcow2 disks support persistent bitmaps", which is why
/// `detect_vm_capabilities` refuses anything else.
///
/// Granularity is left at QEMU's default (64 KiB per
/// `BlockDirtyBitmapAdd.granularity`): a finer bitmap tracks smaller
/// writes but costs more memory per gigabyte of disk, and we have no basis
/// to second-guess the default across an unknown fleet.
pub fn create_bitmap(vm: &str, node: &str) -> Result<(), String> {
    qmp(
        vm,
        "block-dirty-bitmap-add",
        Some(serde_json::json!({
            "node": node,
            "name": bitmap_name(vm),
            "persistent": true,
        })),
    )
    .map(|_| ())
}

/// Remove the bitmap — used to clear an inconsistent one before recreating,
/// and when HA is disabled for the VM so we do not leave state in the image.
pub fn remove_bitmap(vm: &str, node: &str) -> Result<(), String> {
    qmp(
        vm,
        "block-dirty-bitmap-remove",
        Some(serde_json::json!({ "node": node, "name": bitmap_name(vm) })),
    )
    .map(|_| ())
}

/// Virtual size of a qcow2 in bytes, via `qemu-img info --output=json`.
/// The delta target must be created at the same virtual size as the source
/// or the backup job has nowhere to put high-offset clusters.
pub fn virtual_size(disk_path: &str) -> Result<u64, String> {
    let out = Command::new("qemu-img")
        .args(["info", "--output=json", disk_path])
        .output()
        .map_err(|e| format!("qemu-img info: {}", e))?;
    if !out.status.success() {
        return Err(format!(
            "qemu-img info failed for {}: {}",
            disk_path,
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    let v: serde_json::Value = serde_json::from_slice(&out.stdout)
        .map_err(|e| format!("qemu-img info json: {}", e))?;
    v.get("virtual-size")
        .and_then(|s| s.as_u64())
        .ok_or_else(|| format!("qemu-img info gave no virtual-size for {}", disk_path))
}

/// Create the empty qcow2 that will receive the dirty clusters.
fn create_delta_target(path: &str, size: u64) -> Result<(), String> {
    let out = Command::new("qemu-img")
        .args(["create", "-f", "qcow2", path, &size.to_string()])
        .output()
        .map_err(|e| format!("qemu-img create: {}", e))?;
    if !out.status.success() {
        return Err(format!(
            "qemu-img create {} failed: {}",
            path,
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(())
}

/// Poll a block job to a terminal state and report whether it succeeded.
///
/// The job is started with `auto-dismiss: false` so it parks in
/// `concluded` instead of vanishing, which is the only way to read
/// `BlockJobInfo.error` reliably — "Error information if the job did not
/// complete successfully. Not set if the job completed successfully."
/// A job that auto-dismissed would leave us unable to tell success from
/// failure, and guessing that direction means shipping a truncated delta.
///
/// JobStatus values are from qapi/job.json: undefined, created, running,
/// paused, ready, standby, waiting, pending, aborting, concluded, null.
fn await_job(vm: &str, job_id: &str, timeout_secs: u64) -> Result<(), String> {
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(timeout_secs);
    loop {
        let jobs = qmp(vm, "query-block-jobs", None)?;
        let arr = jobs.as_array().cloned().unwrap_or_default();
        // BlockJobInfo.device IS the job identifier ("Originally the device
        // name but other values are allowed since QEMU 2.7").
        let mine = arr.iter().find(|j| {
            j.get("device").and_then(|d| d.as_str()) == Some(job_id)
        });
        match mine {
            None => {
                // Gone without us dismissing it. With auto-dismiss false
                // this should not happen; treat it as failure rather than
                // assume success — a missing job is not evidence of a
                // complete delta.
                return Err(format!(
                    "backup job '{}' disappeared before concluding — treating as failed \
                     so the delta is not trusted",
                    job_id
                ));
            }
            Some(j) => {
                let status = j.get("status").and_then(|s| s.as_str()).unwrap_or("");
                if status == "concluded" || status == "null" {
                    let err = j.get("error").and_then(|e| e.as_str()).map(|s| s.to_string());
                    // Dismiss regardless, or the job leaks in the query list.
                    let _ = qmp(vm, "job-dismiss", Some(serde_json::json!({ "id": job_id })));
                    return match err {
                        Some(e) => Err(format!("backup job failed: {}", e)),
                        None => Ok(()),
                    };
                }
                if status == "aborting" {
                    // Keep waiting — it will reach concluded and carry the
                    // error text, which is more useful than "aborting".
                }
            }
        }
        if std::time::Instant::now() >= deadline {
            // Cancel so a runaway job does not keep writing to a delta we
            // are about to discard.
            let _ = qmp(vm, "block-job-cancel", Some(serde_json::json!({ "device": job_id })));
            return Err(format!(
                "backup job '{}' did not finish within {}s",
                job_id, timeout_secs
            ));
        }
        std::thread::sleep(std::time::Duration::from_millis(500));
    }
}

/// Take an incremental delta of `disk_path` into `out_path`.
///
/// Blocking (QMP is a synchronous socket protocol and the job poll sleeps),
/// so callers must run it off the async runtime.
///
/// On success `out_path` holds a qcow2 containing exactly the clusters the
/// guest dirtied since the last successful round, and the bitmap has been
/// cleared by QEMU (`bitmap-mode: "on-success"`).
pub fn take_incremental(
    vm: &str,
    disk_path: &str,
    out_path: &str,
    timeout_secs: u64,
) -> Result<(), String> {
    let node = resolve_disk_node(vm, disk_path)?;

    // A bitmap that is not recording produces a delta that silently omits
    // guest writes. Refuse rather than ship an incomplete round.
    match bitmap_state(vm, disk_path)? {
        BitmapState::Recording => {}
        BitmapState::Missing => {
            return Err(
                "no dirty bitmap on this VM's disk — a full seed is required before \
                 incremental replication can start"
                    .to_string(),
            );
        }
        BitmapState::NotRecording => {
            return Err(
                "the dirty bitmap has stopped recording, so a delta would omit guest \
                 writes — a full seed is required"
                    .to_string(),
            );
        }
        BitmapState::Inconsistent => {
            return Err(
                "the persistent dirty bitmap was stored improperly (the VM's QEMU was \
                 killed rather than shut down); it cannot be used and a full seed is \
                 required"
                    .to_string(),
            );
        }
    }

    let size = virtual_size(disk_path)?;
    create_delta_target(out_path, size)?;

    // Unique per round so a retry can never collide with a node name still
    // registered from a previous attempt.
    let token = uuid::Uuid::new_v4().simple().to_string();
    let target_node = format!("wolfha-tgt-{}", token);
    let job_id = format!("wolfha-job-{}", token);

    // blockdev-add: BlockdevOptions with driver qcow2 over a file protocol
    // node. The target must exist as a node before blockdev-backup can
    // reference it — `BlockdevBackup.target` is a node name, not a path.
    let add = qmp(
        vm,
        "blockdev-add",
        Some(serde_json::json!({
            "driver": "qcow2",
            "node-name": target_node,
            "file": { "driver": "file", "filename": out_path },
        })),
    );
    if let Err(e) = add {
        let _ = std::fs::remove_file(out_path);
        return Err(format!("could not attach the delta target: {}", e));
    }

    // Always detach the target node, whatever happens next — a leaked node
    // pins the delta file open and the next round's name would differ,
    // accumulating nodes for the life of the VM process.
    let detach = |vm: &str, node: &str| {
        let _ = qmp(vm, "blockdev-del", Some(serde_json::json!({ "node-name": node })));
    };

    // sync: "bitmap" + bitmap-mode: "on-success" — copy only what the
    // bitmap describes, and clear those bits only if the job succeeds, so
    // a failed job leaves the dirty set intact for the next attempt.
    // (MirrorSyncMode and BitmapSyncMode spellings from block-core.json.)
    let backup = qmp(
        vm,
        "blockdev-backup",
        Some(serde_json::json!({
            "job-id": job_id,
            "device": node,
            "target": target_node,
            "sync": "bitmap",
            "bitmap": bitmap_name(vm),
            "bitmap-mode": "on-success",
            // Park in `concluded` so the outcome can be read — see await_job.
            "auto-dismiss": false,
        })),
    );
    if let Err(e) = backup {
        detach(vm, &target_node);
        let _ = std::fs::remove_file(out_path);
        return Err(format!("could not start the incremental backup: {}", e));
    }

    let result = await_job(vm, &job_id, timeout_secs);
    detach(vm, &target_node);
    if let Err(e) = result {
        let _ = std::fs::remove_file(out_path);
        return Err(e);
    }
    Ok(())
}

/// Apply a received delta onto this node's copy of the disk. Replica side.
///
/// `qemu-img rebase -u` changes only the backing pointer, with no data
/// movement and no check of the contents ("only the backing file name and
/// format of FILENAME is changed without any checks on the file contents"),
/// which is exactly right here: the delta was taken against the same base
/// content the replica holds, so retargeting it is safe, whereas a safe-mode
/// rebase would try to merge against the OLD backing file and is described
/// as "an expensive operation, comparable to converting an image".
///
/// `qemu-img commit` then writes the delta's recorded clusters down into
/// that backing file. `-d` skips emptying the delta afterwards, since we
/// delete it.
pub fn apply_delta(delta_path: &str, target_disk: &str) -> Result<(), String> {
    if !std::path::Path::new(target_disk).exists() {
        return Err(format!(
            "cannot apply a delta: this node has no copy of {} — a full seed is required first",
            target_disk
        ));
    }
    let rebase = Command::new("qemu-img")
        .args(["rebase", "-u", "-b", target_disk, "-F", "qcow2", delta_path])
        .output()
        .map_err(|e| format!("qemu-img rebase: {}", e))?;
    if !rebase.status.success() {
        return Err(format!(
            "qemu-img rebase failed: {}",
            String::from_utf8_lossy(&rebase.stderr).trim()
        ));
    }
    let commit = Command::new("qemu-img")
        .args(["commit", "-d", delta_path])
        .output()
        .map_err(|e| format!("qemu-img commit: {}", e))?;
    if !commit.status.success() {
        return Err(format!(
            "qemu-img commit failed: {}",
            String::from_utf8_lossy(&commit.stderr).trim()
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verified against a live QEMU: `query-block` reports the filename as
    /// QEMU was launched with, not the absolute path we hold. An exact
    /// comparison found no disk at all, which would have made VM
    /// replication non-functional.
    #[test]
    fn a_disk_is_matched_despite_path_form() {
        assert!(same_disk("/var/lib/wolfstack/vms/web01.qcow2", "/var/lib/wolfstack/vms/web01.qcow2"));
        // The live failure: relative on one side, absolute on the other.
        assert!(same_disk("web01.qcow2", "/var/lib/wolfstack/vms/web01.qcow2"));
        assert!(same_disk("./web01.qcow2", "/srv/vms/web01.qcow2"));
    }

    /// Different disks must never be conflated — that would attach the
    /// bitmap to, and later back up, the wrong image.
    #[test]
    fn different_disks_do_not_match() {
        assert!(!same_disk("web02.qcow2", "/var/lib/wolfstack/vms/web01.qcow2"));
        assert!(!same_disk("", "/var/lib/wolfstack/vms/web01.qcow2"));
        assert!(!same_disk("/var/lib/wolfstack/vms/db.qcow2", "/var/lib/wolfstack/vms/web01.qcow2"));
    }

    /// Match strength orders the candidates, so an exact path always wins
    /// over a mere file-name coincidence. Without the ordering, a VM with a
    /// second disk of the same name elsewhere could have the bitmap
    /// attached to the wrong image.
    #[test]
    fn an_exact_path_outranks_a_name_coincidence() {
        let want = "/var/lib/wolfstack/vms/web01.qcow2";
        assert_eq!(match_strength(want, want), Some(0));
        assert_eq!(match_strength("/srv/other/web01.qcow2", want), Some(2));
        assert_eq!(match_strength("/srv/other/db.qcow2", want), None);
        // Ordering is what the resolver relies on.
        assert!(match_strength(want, want) < match_strength("/srv/other/web01.qcow2", want));
    }

    #[test]
    fn bitmap_name_is_namespaced_per_vm() {
        assert_eq!(bitmap_name("web01"), "wolfha-web01");
        assert_ne!(bitmap_name("a"), bitmap_name("b"));
    }

    /// BlockDirtyBitmapAdd caps the name at 1024 bytes. VM names are
    /// already validated upstream, but the prefix must not be what pushes
    /// a legitimate name over.
    #[test]
    fn bitmap_name_stays_within_the_qmp_limit() {
        let long_vm = "v".repeat(900);
        assert!(bitmap_name(&long_vm).len() < 1024);
    }

    /// A delta must never be applied onto a node with no base image —
    /// committing into a missing backing file is how you get a disk that
    /// contains only the changed clusters and nothing else.
    #[test]
    fn apply_delta_refuses_without_a_base_image() {
        let err = apply_delta("/nonexistent/delta.qcow2", "/nonexistent/base.qcow2")
            .expect_err("must refuse");
        assert!(err.contains("full seed"), "should demand a seed: {}", err);
    }

    /// Pending deltas cross the wire and are persisted in wolfha.json, so
    /// an older payload without `applied_by` must still parse.
    #[test]
    fn pending_delta_tolerates_missing_applied_by() {
        let d: PendingDelta =
            serde_json::from_str(r#"{"path":"/tmp/d.qcow2","taken_at":1}"#).expect("must parse");
        assert!(d.applied_by.is_empty());
    }
}
